;;; syntax-subword-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from syntax-subword.el

(autoload 'syntax-subword-mode "syntax-subword" "\
This mode is like `subword-mode', but also treats syntax

  changes as word boundaries.  Syntax changes are generally the
  same as face changes when font lock is
  enabled. \\{syntax-subword-mode-map}

This is a minor mode.  If called interactively, toggle the
`Syntax-Subword mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `syntax-subword-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-syntax-subword-mode 'globalized-minor-mode t)
(defvar global-syntax-subword-mode nil "\
Non-nil if Global Syntax-Subword mode is enabled.
See the `global-syntax-subword-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-syntax-subword-mode'.")
(custom-autoload 'global-syntax-subword-mode "syntax-subword" nil)
(autoload 'global-syntax-subword-mode "syntax-subword" "\
Toggle Syntax-Subword mode in all buffers.
With prefix ARG, enable Global Syntax-Subword mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Syntax-Subword mode is enabled in all buffers where `(lambda nil
(syntax-subword-mode 1))' would do it.

See `syntax-subword-mode' for more information on Syntax-Subword
mode.

(fn &optional ARG)" t)
(register-definition-prefixes "syntax-subword" '("syntax-subword-"))

;;; End of scraped data

(provide 'syntax-subword-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; syntax-subword-autoloads.el ends here
